name: stomp_sockjs
version: 0.2.0
author: Tamas Kiss <stompsockjsdart@gmail.com>
description: A pub package
homepage: https://github.com/tomikiss/stomp_sockjs
dependencies:
  #sockjs_client: '>= 0.3.0'
  sockjs_client:
    git:
      url: git@github.com:dougreese/sockjs-dart-client.git
      ref: 0.3.0
  stomp: any
